---
title: Charts 3 to Charts 4 Migration Guide
order: 10
layout: page
---

[[charts4.migration]]
= Charts 3 to Charts 4 Migration Guide

[[charts4.migration.introduction]]
== Introduction

Charts 4 is using Vaadin Framework 8.
Before migrating from Charts 3 to Charts 4, you need to migrate your application to Vaadin 8, see Vaadin Framework 8 migration guide.

[[charts4.migration.changes]]
== Changes in Charts 4

Most of Vaadin Charts 3 API is compatible with Vaadin Charts 4.x.
There are two main changes:

* Methods that use [classname]#Date# were deprecated, use [classname]#Instant# instead.
* [classname]#ContainerDataSeries# is deprecated, use [classname]#DataProviderSeries# instead, see <<charts-data#charts.data.dataproviderseries,"instructions">>.

[[charts4.migration.using.compatibility]]
== Using Vaadin Charts compatibility package

During migration from Charts 3 to Charts 4 you may want to use [classname]#ContainerDataSeries#.
To do that, add a dependency to the vaadin-charts-compatibility package:

[subs="normal"]
----
&lt;dependency&gt;
    &lt;groupId&gt;com.vaadin&lt;/groupId&gt;
    &lt;artifactId&gt;vaadin-charts-compatibility&lt;/artifactId&gt;
    &lt;version&gt;[replaceable]##4.0.5##&lt;/version&gt;
&lt;/dependency&gt;
----

Afterwards, change the import statement for ContainerDataSeries to:

[source, java]
----
import com.vaadin.v7.addon.charts.model.ContainerDataSeries;
----
