---
title: Installing Vaadin Charts
order: 2
layout: page
---

[[charts.installing]]
= Installing Vaadin Charts

As with most Vaadin add-ons, you can install Vaadin Charts as a Maven or Ivy
dependency in your project, or from an installation package. For general
instructions on installing add-ons, please see
<<dummy/../../../framework/addons/addons-overview.asciidoc#addons.overview,"Using
Vaadin Add-ons">>.

Vaadin Charts requires Vaadin 7.4 or later.

Using Vaadin Charts requires a license key, which you must install before
compiling the widget set. The widget set must be compiled after setting up the
dependency or library JARs.

For instructions on installing a license key, see <<dummy/../../../framework/addons/addons-cval.asciidoc#,"Installing Commercial Vaadin Add-on License">>.

[[charts.installing.maven]]
== Maven Dependency

The Maven dependency for Vaadin Charts is as follows:

[subs="normal"]
----
&lt;dependency&gt;
    &lt;groupId&gt;com.vaadin.addon&lt;/groupId&gt;
    &lt;artifactId&gt;vaadin-charts&lt;/artifactId&gt;
    &lt;version&gt;[replaceable]##3.2.0##&lt;/version&gt;
&lt;/dependency&gt;
----
You also need to define the Vaadin add-ons repository if not already defined:

[source,xml]
----
<repository>
   <id>vaadin-addons</id>
   <url>http://maven.vaadin.com/vaadin-addons</url>
</repository>
----


[[charts.installing.ivy]]
== Ivy Dependency

The Ivy dependency, to be defined in [filename]#ivy.xml#, would be as follows:

[subs="normal"]
----
&lt;dependency org="com.vaadin" name="vaadin-charts"
            rev="**3.2.0**" /&gt;
----
It is generally recommended to use a fixed version number, but you can also use
[literal]#++latest.release++# to get the latest release.
