language: java
jdk: oraclejdk8
# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

before_install:
  # Disable all Travis default repositories
  - sed -i "s/activeByDefault>true</activeByDefault>false</g"  ~/.m2/settings.xml

# Make Chrome IT tests more stable
addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # The Following line fixes random Chrome startup failures (https://github.com/SeleniumHQ/docker-selenium/issues/87)
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null

script:
  - mvn -B -e -V clean verify

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/flow
  - rm -rf $HOME/.m2/repository/com/vaadin/flow-*
